# Netlify configuration for Gold Pointe COA website

# Headers to enable form handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules for SPA-like navigation
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200

# Password protection for admin interface
[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Build configuration
[build]
  publish = "."
  command = ""

# Exclude original resources file from sitemap but allow admin.html
[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    exclude = [
      "resources-original.html",
      "admin-encrypt.html",
      "encrypt-resources.js"
    ]