# Netlify configuration for Gold Pointe COA website

# Headers to enable form handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Prevent access to admin-encrypt.html - redirect to 404
[[redirects]]
  from = "/admin-encrypt.html"
  to = "/404.html"
  status = 404
  force = true

# Prevent access to README.md - redirect to 404
[[redirects]]
  from = "/README.md"
  to = "/404.html"
  status = 404
  force = true

# Prevent access to resources-original.html - redirect to 404
[[redirects]]
  from = "/resources-original.html"
  to = "/404.html"
  status = 404
  force = true

# Redirect rules for contact success page
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200

# Custom 404 page configuration
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Build configuration
[build]
  publish = "."
  command = ""

# Exclude admin tools and original resources file from sitemap
[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    exclude = [
      "resources-original.html",
      "admin-encrypt.html",
      "README.md",
      "404.html"
    ]