# Netlify configuration for Gold Pointe COA website

# Headers to enable form handling
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules for SPA-like navigation
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200

# Build configuration
[build]
  publish = "."
  command = ""

# Exclude admin tools and original resources file from sitemap
[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    exclude = [
      "resources-original.html",
      "admin.html",
      "admin-encrypt.html",
      "encrypt-resources.js",
      "README.md"
    ]